---
# tasks file for vcd_external_networks

- name: criando rede externa
  vcd_external_network:
    vc_name: vc.0
    port_group_names:
        - VM Network
    network_name: external-network
    gateway_ip: 10.176.3.253
    netmask: 255.255.0.0
    ip_ranges:
        - 10.176.7.68-10.176.7.69
    state: "present"
  register: output

- name: create external network output
  debug:
    msg: '{{ output }}'
